service: employee-creator

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: ap-southeast-2
  role: arn:aws:iam::${aws:accountId}:role/employee_creator

functions:
  createEmployee:
    handler: src/handlers/createEmployee.handler
    events:
      - http:
          path: /employees
          method: POST
  viewAllEmployees:
    handler: src/handlers/viewAllEmployees.handler
    events:
      - http:
          path: /employees
          method: GET
  viewEmployeeById:
    handler: src/handlers/viewEmployeeById.handler
    events:
      - http:
          path: /employees/{employeeId}
          method: GET
          request:
            parameters:
              paths:
                employeeId: true

resources:
  Resources:
    EmployeesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
